<?php
/******************************************************************************
 * NINA VIỆT NAM
 * Email: nina@nina.vn
 * Website: nina.vn
 * Version: 1.0
 * Đây là tài sản của CÔNG TY TNHH TM DV NINA. Vui lòng không sử dụng khi chưa được phép.
 */

return [
    'logo' => [
        'title_main' => "Logo",
        'kind' => 'static',
        'title' => true,
        'desc' => false,
        'desc_cke' => false,
        'status' => ["hienthi" => "Hiển thị"],
        'images' => true,
        'width' => 185,
        'height' => 95,
        'thumb' => '185x95x2',
    ],
    'banner' => [
        'title_main' => "Banner",
        'kind' => 'static',
        'desc' => false,
        'desc_cke' => false,
        'status' => ["hienthi" => "Hiển thị"],
        'images' => true,
        'width' => 465,
        'height' => 75,
        'thumb' => '465x75x2',
    ],
    'banner-quang-cao-1' => [
        'title_main' => "Banner quảng cáo 1",
        'kind' => 'static',
        'desc' => false,
        'desc_cke' => false,
        'status' => ["hienthi" => "Hiển thị"],
        'images' => true,
        'width' => 1366,
        'height' => 500,
        'link' => true,
        'thumb' => '500x300x2',
    ],

    'banner-quang-cao-2' => [
        'title_main' => "Banner quảng cáo 2",
        'kind' => 'static',
        'desc' => false,
        'desc_cke' => false,
        'status' => ["hienthi" => "Hiển thị"],
        'images' => true,
        'width' => 1366,
        'height' => 595,
        'link' => true,
        'thumb' => '500x300x2',
    ],
    'favicon' => [
        'title_main' => "Favicon",
        'kind' => 'static',
        'status' => ["hienthi" => "Hiển thị"],
        'images' => true,
        'width' => 48,
        'height' => 48,
        'thumb' => '48x48x2',
    ],
    'slide' => [
        'title_main' => "Slideshow",
        'kind' => 'album',
        'status' => ["hienthi" => "Hiển thị"],
        'number' => 5,
        'title' => true,
        'images' => true,
        'show_images' => true,
        'gallery' => true,
        'link' => true,
        'name' => true,
        'desc' => false,
        'width' => 1366,
        'height' => 600,
        'thumb' => '100x100x1',
    ],
    'tieu-chi' => [
        'title_main' => "Tiêu chí",
        'kind' => 'album',
        'status' => ["hienthi" => "Hiển thị"],
        'number' => 5,
        'title' => true,
        'images' => true,
        'show_images' => true,
        'gallery' => true,
        'desc' => true,
        'name' => true,
        'width' => 100,
        'height' => 100,
        'thumb' => '100x100x2',
    ],

    'video' => [
        'title_main' => "Video",
        'kind' => 'album',
        'status' => ["noibat" => "Nổi bật","hienthi" => "Hiển thị"],
        'number' => 4,
        'show_images' => true,
        'images' => true,
        'avatar' => true,
        'link_video' => true,
        'name' => true,
        'desc' => false,
        'width' => 550,
        'height' => 350,
        'thumb' => '100x100x1',
    ],
    'social' => [
        'title_main' => "Mạng xã hội 1",
        'kind' => 'album',
        'status' => ["hienthi" => "Hiển thị"],
        'number' => 4,
        'show_images' => true,
        'images' => true,
        'avatar' => true,
        'link' => true,
        'name' => true,
        'desc' => false,
        'width' => 40,
        'height' => 40,
        'thumb' => '40x40x1',
    ],
    // 'social2' => [
    //     'title_main' => "Mạng xã hội 2",
    //     'kind' => 'album',
    //     'status' => ["hienthi" => "Hiển thị"],
    //     'number' => 4,
    //     'show_images' => true,
    //     'images' => true,
    //     'avatar' => true,
    //     'link' => true,
    //     'name' => true,
    //     'desc' => false,
    //     'width' => 40,
    //     'height' => 40,
    //     'thumb' => '40x40x1',
    // ],
    // 'doi-tac' => [
    //     'title_main' => "Đối tác",
    //     'kind' => 'album',
    //     'status' => ["hienthi" => "Hiển thị"],
    //     'number' => 4,
    //     'show_images' => true,
    //     'images' => true,
    //     'avatar' => true,
    //     'link' => true,
    //     'name' => true,
    //     'desc' => false,
    //     'width' => 165,
    //     'height' => 90,
    //     'thumb' => '100x100x2',
    // ],
    'watermark_product' => [
        'title_main' => "Con dấu sản phẩm",
        'kind' => 'static',
        'watermark' =>true,
        'desc' => false,
        'title' => false,
        'desc_cke' => false,
        'link' => false,
        'status' => ["hienthi" => "Hiển thị"],
        'images' => true,
        'width' => 70,
        'height' => 70,
        'thumb' => '70x70x1',
    ]
];